### ISSUE TITLE
コンテンツの内容の不備

### ISSUE THREAD

**Issue by ogatodesuyo** [shataku/gourmet#11]
### <h1>URL<h1>
[リンク1](https://shataku.github.io/gourmet/)
### 問題内容
トップページ1項目のセブンイレブンの説明に誤表記がある
ラーメンフェアが終わった今セブンイレブンにすべてが揃っているとは言い難い
### 期待される結果
セブンイレブン→ファミリーマート
### ブラウザバージョン
Chrome　80.0.3987.163
### 該当画面
![gourmet_issues](https://user-images.githubusercontent.com/64000936/79743895-6262a900-8340-11ea-8496-a40066903b93.PNG)

担当　ハナハナワークス　おがとまる

**Comment by nchiba** [comment]
「この世のすべて」→「アメリカ発祥」とし、ファミリーマート項目を追加するのはどうか。

**Comment by campa-rabb** [comment]
SUNABACO周辺の飲食施設というインデックス目的の以上、SUNABACOからの距離は重要なファクターとして置くべきであると考える。

したがって、セブンイレブンを無くすのではなくファミリーマート項目を追加するという意見に賛同する。

descriptionに関しては「この世のすべて」→「近くて便利」とすればセブン&アイ・ホールディングスの発言でもあり信頼性が高いと思われる。

**Comment by nchiba** [comment]
上記を踏まえてプルリクエストを出す。検討願いたい。
